
/*******************************************************
 * Code Generated By CoFramework?LISENCE Apache 2.0? 
 * DateTime : 2023/6/30 18:39:09
 * UVersion : 2021.3.24f1c1
 *******************************************************/
using CoFramework.RefBuild;

namespace CoFramework.RefBuild.Cache
{
    public partial class Square : MonoBehaviour
    {
            public UnityEngine.Transform Square_Transform_0 {get;set;}=default;
    Square_Transform_0 = GetComponent<UnityEngine.Transform>();
    public BindableProperty<UnityEngine.Vector3> Square_Transform_position {get;set;}=default;
    Square_Transform_position = new BindableProperty<UnityEngine.Vector3>(()=>Square_Transform.position,(x)=>Square_Transform.position=x,False);


        public void InitRefs()
        {
            
        }
    }
    
private void Awake()
{
    InitRefs();
}

}
